name: bathing_spots_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^13.0.2

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.17.0
  provider: ^6.1.5+1
  http: ^1.6.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  flutter_map: ^8.3.0
    flutter_map_tile_caching: ^9.0.0
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - data/icons/
    - data/logos_departements/france/pays_de_la_loire/
    - data/logos_communes/france/pays_de_la_loire/vendee/