// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7I178fok0VKB_aClp_dDgJdhAa5a9rJU',
    appId: '1:582503168867:web:19aacebc4be3aec9db7156',
    messagingSenderId: '582503168867',
    projectId: 'sphot-ab80b',
    authDomain: 'sphot-ab80b.firebaseapp.com',
    storageBucket: 'sphot-ab80b.firebasestorage.app',
    measurementId: 'G-455J4VTGXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNn9fur3Er1sWXRIi1B2bIOVKLKHcguSA',
    appId: '1:582503168867:android:aaff341684299eebdb7156',
    messagingSenderId: '582503168867',
    projectId: 'sphot-ab80b',
    storageBucket: 'sphot-ab80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzrAfmDV4I3IamrmneGREjg6NiYPSM5g',
    appId: '1:582503168867:ios:163b49d1edc67afadb7156',
    messagingSenderId: '582503168867',
    projectId: 'sphot-ab80b',
    storageBucket: 'sphot-ab80b.firebasestorage.app',
    iosBundleId: 'com.example.bathingSpotsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzrAfmDV4I3IamrmneGREjg6NiYPSM5g',
    appId: '1:582503168867:ios:163b49d1edc67afadb7156',
    messagingSenderId: '582503168867',
    projectId: 'sphot-ab80b',
    storageBucket: 'sphot-ab80b.firebasestorage.app',
    iosBundleId: 'com.example.bathingSpotsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7I178fok0VKB_aClp_dDgJdhAa5a9rJU',
    appId: '1:582503168867:web:21f4ffee9d7efffedb7156',
    messagingSenderId: '582503168867',
    projectId: 'sphot-ab80b',
    authDomain: 'sphot-ab80b.firebaseapp.com',
    storageBucket: 'sphot-ab80b.firebasestorage.app',
    measurementId: 'G-WMXDEWS5G2',
  );
}